# ---- build stage ----
FROM node:20-alpine AS build
WORKDIR /app

# hanya kalau ada package-lock.json
COPY apps/web-user/package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

# salin source
COPY apps/web-user/ .

# build assets
RUN npm run build

# ---- runtime stage (nginx) ----
FROM nginx:1.25-alpine
COPY apps/web-user/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3001
