# ---- build stage ----
FROM node:20-alpine AS build
WORKDIR /app
COPY apps/web-user/package*.json ./
# gunakan npm (tanpa pnpm)
RUN if [ -f package-lock.json ]; then npm ci --omit=optional; else npm install --omit=optional; fi
COPY apps/web-user/ .
RUN npm run build

# ---- runtime (nginx) ----
FROM nginx:1.25-alpine
# nginx.conf khusus User UI
COPY apps/web-user/nginx.conf /etc/nginx/conf.d/default.conf
# hasil build SPA
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3001
