services:
  web-admin:
    # kosongkan command & volumes agar tidak menjalankan "npm run dev"
    command: []
    volumes: []
    depends_on:
      - gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
