services:
  gateway:
    ports:
      - "127.0.0.1:11800:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web-admin:
    depends_on:
      gateway:
        condition: service_healthy
    ports:
      - "127.0.0.1:11802:3002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
