services:
  gateway:
    healthcheck:
      # pakai Node fetch (ada di Node 20) agar tidak perlu curl/wget
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:3000/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 15s
      timeout: 5s
      retries: 5
