FROM node:20-alpine

WORKDIR /app

# pakai path dari root repo karena compose build konteksnya '.'
COPY services/gateway/package*.json ./
RUN npm ci || npm i --omit=optional

# salin source
COPY services/gateway/server.js ./server.js
COPY services/gateway/src ./src

EXPOSE 3000
CMD ["node","server.js"]
