FROM node:20-alpine AS build
WORKDIR /app
COPY package.json ./
RUN npm ci || npm install
COPY . .
RUN npm i -g pnpm@9
RUN npm run build

FROM nginx:1.25-alpine
COPY apps/web-admin/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 3002
CMD ["nginx","-g","daemon off;"]
