FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=development
COPY apps/web-admin/package.json ./package.json
RUN npm install --omit=optional || npm install
COPY apps/web-admin/server.js ./server.js
EXPOSE 3002
CMD ["npm","run","dev"]
